name: story
description: Create a story| 创建一个需求
labels: ""
body:
  - type: markdown
    attributes:
      value: 请务必**认真填写**需求内容

  - type: dropdown
    attributes:
      label: 需求复杂度
      multiple: false
      options:
        - 简单
        - 一般
        - 复杂
       

  - type: textarea
    attributes:
      label: 需求来源
      description: 请描述需求的背景/场景/产生的来源
    validations:
      required: true

  - type: textarea
    attributes:
      label: 验收标准
      description: 请分条描述需求验收标准
      value: |
        1.
        2.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 关联task
      description: 请使用add tasklist方式关联此需求对应的任务

