---
name: User Story
about: Create a user story
title: 'As a ..., I want to ..., so I can ...'
labels: "Story"

---
<!-- A well crafted user story is curcial for development and a successful delivery. Please fill in this form carefully. The paragraph and text in <> below are comments, no need to delete -->

### User story
<!-- summarize the user story -->
**As a** _, **I want** _ **so that** _.

<!-- elaborate more if needed -->

### Resources:
<!-- add link to PRD, design file and other useful resources -->
- PRD: 
- Design:
- Other:

### Acceptance criteria
<!-- describe the acceptance criteria so can be verified by QA -->
- 

### Todo
<!-- for developers to break down tasks if needed -->

- [ ] 

### Major Risk & Detection
<!-- for developers to fill into potential major risk involved, to help QA identify risks and allow QA to find the right person 
(Give as much info as possible) -->
<!-- 
Example:
1. Sensitive message won't be blocked
- Risk : 
Aliyun return api result inconsistent, especially for new registered users (new male users send sensitive message to female users) 
This issue usually happened during peak hours, eg. from 9pm to 12am

- Detection (Developers to give easy ways to detect the issue): 
a. Find the specific return data using tracker `TEST_TRACKER_NAME` and look for `result`. Compared this actual result to the expected result.
(This test tracker is solely for development testing purpose, it won't be released to production)

b. In Guagua, look for the api `room/detectSensitiveMsg`, response param `isCleanMsg`.
This test response correspond to the result retrieve from the aliyun
This test response will be deleted in production and it is solely for testing purpose

- Solution/Updates (Resolved Date: 7 July 2023):
a. Reroute the request to our own sensitive message detection team, internal team more reliable than third party. But this can only be done after 26 July when the internal team completes the requirements.
b. In the meanwhile, PM accept the risks where this event may occurs (at least it is better than before, when there is no blocking of sensitive message at all)
-->
1. 
