name: Story
description: Create a story | 创建一个story
labels:
body:
 - type: dropdown
    attributes:
      label: 需求复杂程度
      multiple: false
      options:
        - 简单
        - 一般
        - 复杂
       

  - type: textarea
    attributes:
      label: 需求来源
      description: 请描述需求的背景/场景/产生此需求的原因
     
