name: story
description: Create a story| 创建一个需求
labels: “”
body:
  - type: markdown
    attributes:
      value: 请务必**认真填写**需求内容

  - type: dropdown
    attributes:
      label: 1、需求复杂度-test
      multiple: false
      options:
        - 简单需求
        - 普通需求
        - 复杂需求
        - 非常复杂需求
       

  - type: textarea
    attributes:
      label: 2、需求来源
      description: 请描述需求的背景/场景/产生的来源
    validations:
      required: true

  - type: textarea
    attributes:
      label: 3、验收标准
      description: 请分条描述需求验收标准
      value: |
        1.
        2.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 4、关联task-test
      description: 测试pr功能

