name: Update Project Items
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: olaola-chat/agilekit-ts@main
        with:
          ghToken: ${{ secrets.PAT_MANAGE_PROJECT }}
          organization: olaola-chat
          projectNumber: 106
          upstreamProjectNumber: 106
        

          

    